[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; 1. Automatically download the graphics library
lib_deps = 
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/pschatzmann/ESP32-A2DP.git


; 2. Inject your hardware layout straight into the library setup
build_flags =
  -D USER_SETUP_LOADED=1
  -D ILI9341_DRIVER=1
  -D TFT_MISO=5
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=27
  -D TFT_DC=2
  -D TFT_RST=19
  -D TFT_BL=4
  -D TFT_BACKLIGHT_ON=HIGH
  -D LOAD_GLCD=1  ; Standard small font
  -D LOAD_FONT2=1 ; Medium font
  -D LOAD_FONT4=1 ; Large font